### ISSUE TITLE
nicer default hover styling

### ISSUE THREAD

**Issue by ImLunaHey** [acao/codemirror-json-schema#157]
current:
<img width="732" alt="Image" src="https://github.com/user-attachments/assets/1a667900-65c6-4b41-9a13-2ce0dfa35429" />

suggested:
<img width="730" alt="Image" src="https://github.com/user-attachments/assets/256d5f6a-86f3-475d-bf02-6f15dfe11870" />

```css
.cm-tooltip-above {   
    /* Make it look distinct */
    background-color: #333 !important;
    color: white !important;
    border: 1px solid #555 !important;
    border-radius: 4px !important;
    box-shadow: 0 2px 8px rgba(0,0,0,0.3) !important;
    
    /* Make sure it has good padding */
    padding: 8px 12px !important;
    
    /* Set width constraints */
    max-width: 90% !important;
    width: auto !important;
    
    /* Improve text display */
    font-size: 13px !important;
    line-height: 1.4 !important;
  }
```
